---
- name: Copy vector config
  copy:
    src: "{{ item }}"
    dest: /opt/vector
  with_fileglob:
    - "*.toml"

- name: Run vector container
  docker_container:
    name: vector
    image: vector:latest
    state: started
    recreate: yes
    env:
      DOCKER_HOST: unix:///var/run/docker.sock
    published_ports:
      - '8383:8383'
    volumes:
      - '/opt/vector/:/etc/vector/'
      - '/opt/logs/:/logs/'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
    - name: logging