---
- name: Run zookeeper
  docker_container:
    name: zookeeper
    image: zookeeper:latest
    state: started
    recreate: yes
    env:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    published_ports:
      - '22181:2181'
    networks:
    - name: logging

- name: Run kafka
  docker_container:
    name: kafka
    image: kafka:latest 
    state: started
    recreate: yes
    env:
      KAFKA_ZK_CONNECT: zookeeper:2181
      KAFKA_PORT: 9092
      KAFKA_ADV_LIST: kafka:9092
      KAFKA_TOPIC: nginx_error_log nginx_access_log grafana_logs
    published_ports:
      - '29092:29092'
    links:
      - 'zookeeper:zookeeper'
    networks:
    - name: logging

- name: Create kafka topics
  shell: sleep 60 && docker exec kafka /opt/create_topic.sh