---
- name: Run elasticsearch
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    state: started
    recreate: yes
    env:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      node.name: elastic_1
    published_ports:
      - '9200:9200'
    networks:
    - name: logging